# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kuril/workspace/DamoyeoServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kuril/workspace/DamoyeoServer

# Include any dependencies generated for this target.
include src/CMakeFiles/../TOMSA.dir/depend.make

# Include the progress variables for this target.
include src/CMakeFiles/../TOMSA.dir/progress.make

# Include the compile flags for this target's objects.
include src/CMakeFiles/../TOMSA.dir/flags.make

src/CMakeFiles/../TOMSA.dir/main.o: src/CMakeFiles/../TOMSA.dir/flags.make
src/CMakeFiles/../TOMSA.dir/main.o: src/main.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/kuril/workspace/DamoyeoServer/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object src/CMakeFiles/../TOMSA.dir/main.o"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../TOMSA.dir/main.o -c /home/kuril/workspace/DamoyeoServer/src/main.cpp

src/CMakeFiles/../TOMSA.dir/main.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../TOMSA.dir/main.i"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/kuril/workspace/DamoyeoServer/src/main.cpp > CMakeFiles/../TOMSA.dir/main.i

src/CMakeFiles/../TOMSA.dir/main.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../TOMSA.dir/main.s"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/kuril/workspace/DamoyeoServer/src/main.cpp -o CMakeFiles/../TOMSA.dir/main.s

src/CMakeFiles/../TOMSA.dir/main.o.requires:

.PHONY : src/CMakeFiles/../TOMSA.dir/main.o.requires

src/CMakeFiles/../TOMSA.dir/main.o.provides: src/CMakeFiles/../TOMSA.dir/main.o.requires
	$(MAKE) -f src/CMakeFiles/../TOMSA.dir/build.make src/CMakeFiles/../TOMSA.dir/main.o.provides.build
.PHONY : src/CMakeFiles/../TOMSA.dir/main.o.provides

src/CMakeFiles/../TOMSA.dir/main.o.provides.build: src/CMakeFiles/../TOMSA.dir/main.o


src/CMakeFiles/../TOMSA.dir/Line.o: src/CMakeFiles/../TOMSA.dir/flags.make
src/CMakeFiles/../TOMSA.dir/Line.o: src/Line.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/kuril/workspace/DamoyeoServer/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object src/CMakeFiles/../TOMSA.dir/Line.o"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../TOMSA.dir/Line.o -c /home/kuril/workspace/DamoyeoServer/src/Line.cpp

src/CMakeFiles/../TOMSA.dir/Line.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../TOMSA.dir/Line.i"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/kuril/workspace/DamoyeoServer/src/Line.cpp > CMakeFiles/../TOMSA.dir/Line.i

src/CMakeFiles/../TOMSA.dir/Line.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../TOMSA.dir/Line.s"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/kuril/workspace/DamoyeoServer/src/Line.cpp -o CMakeFiles/../TOMSA.dir/Line.s

src/CMakeFiles/../TOMSA.dir/Line.o.requires:

.PHONY : src/CMakeFiles/../TOMSA.dir/Line.o.requires

src/CMakeFiles/../TOMSA.dir/Line.o.provides: src/CMakeFiles/../TOMSA.dir/Line.o.requires
	$(MAKE) -f src/CMakeFiles/../TOMSA.dir/build.make src/CMakeFiles/../TOMSA.dir/Line.o.provides.build
.PHONY : src/CMakeFiles/../TOMSA.dir/Line.o.provides

src/CMakeFiles/../TOMSA.dir/Line.o.provides.build: src/CMakeFiles/../TOMSA.dir/Line.o


src/CMakeFiles/../TOMSA.dir/Position.o: src/CMakeFiles/../TOMSA.dir/flags.make
src/CMakeFiles/../TOMSA.dir/Position.o: src/Position.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/kuril/workspace/DamoyeoServer/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object src/CMakeFiles/../TOMSA.dir/Position.o"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../TOMSA.dir/Position.o -c /home/kuril/workspace/DamoyeoServer/src/Position.cpp

src/CMakeFiles/../TOMSA.dir/Position.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../TOMSA.dir/Position.i"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/kuril/workspace/DamoyeoServer/src/Position.cpp > CMakeFiles/../TOMSA.dir/Position.i

src/CMakeFiles/../TOMSA.dir/Position.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../TOMSA.dir/Position.s"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/kuril/workspace/DamoyeoServer/src/Position.cpp -o CMakeFiles/../TOMSA.dir/Position.s

src/CMakeFiles/../TOMSA.dir/Position.o.requires:

.PHONY : src/CMakeFiles/../TOMSA.dir/Position.o.requires

src/CMakeFiles/../TOMSA.dir/Position.o.provides: src/CMakeFiles/../TOMSA.dir/Position.o.requires
	$(MAKE) -f src/CMakeFiles/../TOMSA.dir/build.make src/CMakeFiles/../TOMSA.dir/Position.o.provides.build
.PHONY : src/CMakeFiles/../TOMSA.dir/Position.o.provides

src/CMakeFiles/../TOMSA.dir/Position.o.provides.build: src/CMakeFiles/../TOMSA.dir/Position.o


src/CMakeFiles/../TOMSA.dir/ConcavetToConvex.o: src/CMakeFiles/../TOMSA.dir/flags.make
src/CMakeFiles/../TOMSA.dir/ConcavetToConvex.o: src/ConcavetToConvex.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/kuril/workspace/DamoyeoServer/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object src/CMakeFiles/../TOMSA.dir/ConcavetToConvex.o"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../TOMSA.dir/ConcavetToConvex.o -c /home/kuril/workspace/DamoyeoServer/src/ConcavetToConvex.cpp

src/CMakeFiles/../TOMSA.dir/ConcavetToConvex.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../TOMSA.dir/ConcavetToConvex.i"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/kuril/workspace/DamoyeoServer/src/ConcavetToConvex.cpp > CMakeFiles/../TOMSA.dir/ConcavetToConvex.i

src/CMakeFiles/../TOMSA.dir/ConcavetToConvex.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../TOMSA.dir/ConcavetToConvex.s"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/kuril/workspace/DamoyeoServer/src/ConcavetToConvex.cpp -o CMakeFiles/../TOMSA.dir/ConcavetToConvex.s

src/CMakeFiles/../TOMSA.dir/ConcavetToConvex.o.requires:

.PHONY : src/CMakeFiles/../TOMSA.dir/ConcavetToConvex.o.requires

src/CMakeFiles/../TOMSA.dir/ConcavetToConvex.o.provides: src/CMakeFiles/../TOMSA.dir/ConcavetToConvex.o.requires
	$(MAKE) -f src/CMakeFiles/../TOMSA.dir/build.make src/CMakeFiles/../TOMSA.dir/ConcavetToConvex.o.provides.build
.PHONY : src/CMakeFiles/../TOMSA.dir/ConcavetToConvex.o.provides

src/CMakeFiles/../TOMSA.dir/ConcavetToConvex.o.provides.build: src/CMakeFiles/../TOMSA.dir/ConcavetToConvex.o


src/CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.o: src/CMakeFiles/../TOMSA.dir/flags.make
src/CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.o: src/PointInPolygonAlgorithm.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/kuril/workspace/DamoyeoServer/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object src/CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.o"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.o -c /home/kuril/workspace/DamoyeoServer/src/PointInPolygonAlgorithm.cpp

src/CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.i"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/kuril/workspace/DamoyeoServer/src/PointInPolygonAlgorithm.cpp > CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.i

src/CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.s"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/kuril/workspace/DamoyeoServer/src/PointInPolygonAlgorithm.cpp -o CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.s

src/CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.o.requires:

.PHONY : src/CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.o.requires

src/CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.o.provides: src/CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.o.requires
	$(MAKE) -f src/CMakeFiles/../TOMSA.dir/build.make src/CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.o.provides.build
.PHONY : src/CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.o.provides

src/CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.o.provides.build: src/CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.o


src/CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.o: src/CMakeFiles/../TOMSA.dir/flags.make
src/CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.o: src/TimeOptimizationAlgorithm.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/kuril/workspace/DamoyeoServer/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building CXX object src/CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.o"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.o -c /home/kuril/workspace/DamoyeoServer/src/TimeOptimizationAlgorithm.cpp

src/CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.i"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/kuril/workspace/DamoyeoServer/src/TimeOptimizationAlgorithm.cpp > CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.i

src/CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.s"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/kuril/workspace/DamoyeoServer/src/TimeOptimizationAlgorithm.cpp -o CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.s

src/CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.o.requires:

.PHONY : src/CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.o.requires

src/CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.o.provides: src/CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.o.requires
	$(MAKE) -f src/CMakeFiles/../TOMSA.dir/build.make src/CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.o.provides.build
.PHONY : src/CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.o.provides

src/CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.o.provides.build: src/CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.o


src/CMakeFiles/../TOMSA.dir/ODsay.o: src/CMakeFiles/../TOMSA.dir/flags.make
src/CMakeFiles/../TOMSA.dir/ODsay.o: src/ODsay.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/kuril/workspace/DamoyeoServer/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building CXX object src/CMakeFiles/../TOMSA.dir/ODsay.o"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../TOMSA.dir/ODsay.o -c /home/kuril/workspace/DamoyeoServer/src/ODsay.cpp

src/CMakeFiles/../TOMSA.dir/ODsay.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../TOMSA.dir/ODsay.i"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/kuril/workspace/DamoyeoServer/src/ODsay.cpp > CMakeFiles/../TOMSA.dir/ODsay.i

src/CMakeFiles/../TOMSA.dir/ODsay.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../TOMSA.dir/ODsay.s"
	cd /home/kuril/workspace/DamoyeoServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/kuril/workspace/DamoyeoServer/src/ODsay.cpp -o CMakeFiles/../TOMSA.dir/ODsay.s

src/CMakeFiles/../TOMSA.dir/ODsay.o.requires:

.PHONY : src/CMakeFiles/../TOMSA.dir/ODsay.o.requires

src/CMakeFiles/../TOMSA.dir/ODsay.o.provides: src/CMakeFiles/../TOMSA.dir/ODsay.o.requires
	$(MAKE) -f src/CMakeFiles/../TOMSA.dir/build.make src/CMakeFiles/../TOMSA.dir/ODsay.o.provides.build
.PHONY : src/CMakeFiles/../TOMSA.dir/ODsay.o.provides

src/CMakeFiles/../TOMSA.dir/ODsay.o.provides.build: src/CMakeFiles/../TOMSA.dir/ODsay.o


# Object files for target ../TOMSA
__/TOMSA_OBJECTS = \
"CMakeFiles/../TOMSA.dir/main.o" \
"CMakeFiles/../TOMSA.dir/Line.o" \
"CMakeFiles/../TOMSA.dir/Position.o" \
"CMakeFiles/../TOMSA.dir/ConcavetToConvex.o" \
"CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.o" \
"CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.o" \
"CMakeFiles/../TOMSA.dir/ODsay.o"

# External object files for target ../TOMSA
__/TOMSA_EXTERNAL_OBJECTS =

src/../TOMSA: src/CMakeFiles/../TOMSA.dir/main.o
src/../TOMSA: src/CMakeFiles/../TOMSA.dir/Line.o
src/../TOMSA: src/CMakeFiles/../TOMSA.dir/Position.o
src/../TOMSA: src/CMakeFiles/../TOMSA.dir/ConcavetToConvex.o
src/../TOMSA: src/CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.o
src/../TOMSA: src/CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.o
src/../TOMSA: src/CMakeFiles/../TOMSA.dir/ODsay.o
src/../TOMSA: src/CMakeFiles/../TOMSA.dir/build.make
src/../TOMSA: src/CMakeFiles/../TOMSA.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/kuril/workspace/DamoyeoServer/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Linking CXX executable ../TOMSA"
	cd /home/kuril/workspace/DamoyeoServer/src && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../TOMSA.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
src/CMakeFiles/../TOMSA.dir/build: src/../TOMSA

.PHONY : src/CMakeFiles/../TOMSA.dir/build

src/CMakeFiles/../TOMSA.dir/requires: src/CMakeFiles/../TOMSA.dir/main.o.requires
src/CMakeFiles/../TOMSA.dir/requires: src/CMakeFiles/../TOMSA.dir/Line.o.requires
src/CMakeFiles/../TOMSA.dir/requires: src/CMakeFiles/../TOMSA.dir/Position.o.requires
src/CMakeFiles/../TOMSA.dir/requires: src/CMakeFiles/../TOMSA.dir/ConcavetToConvex.o.requires
src/CMakeFiles/../TOMSA.dir/requires: src/CMakeFiles/../TOMSA.dir/PointInPolygonAlgorithm.o.requires
src/CMakeFiles/../TOMSA.dir/requires: src/CMakeFiles/../TOMSA.dir/TimeOptimizationAlgorithm.o.requires
src/CMakeFiles/../TOMSA.dir/requires: src/CMakeFiles/../TOMSA.dir/ODsay.o.requires

.PHONY : src/CMakeFiles/../TOMSA.dir/requires

src/CMakeFiles/../TOMSA.dir/clean:
	cd /home/kuril/workspace/DamoyeoServer/src && $(CMAKE_COMMAND) -P CMakeFiles/../TOMSA.dir/cmake_clean.cmake
.PHONY : src/CMakeFiles/../TOMSA.dir/clean

src/CMakeFiles/../TOMSA.dir/depend:
	cd /home/kuril/workspace/DamoyeoServer && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/kuril/workspace/DamoyeoServer /home/kuril/workspace/DamoyeoServer/src /home/kuril/workspace/DamoyeoServer /home/kuril/workspace/DamoyeoServer/src /home/kuril/workspace/DamoyeoServer/src/TOMSA.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : src/CMakeFiles/../TOMSA.dir/depend

