# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

src/TOMSA.dir/ConcavetToConvex.o: src/ConcavetToConvex.cpp
src/TOMSA.dir/ConcavetToConvex.o: header/ConcavetToConvex.h
src/TOMSA.dir/ConcavetToConvex.o: header/Line.h
src/TOMSA.dir/ConcavetToConvex.o: header/PointInPolygonAlgorithm.h
src/TOMSA.dir/ConcavetToConvex.o: header/Position.h

src/TOMSA.dir/Line.o: src/Line.cpp
src/TOMSA.dir/Line.o: header/Line.h
src/TOMSA.dir/Line.o: header/Position.h

src/TOMSA.dir/ODsay.o: src/ODsay.cpp
src/TOMSA.dir/ODsay.o: header/ODsay.h
src/TOMSA.dir/ODsay.o: header/Position.h
src/TOMSA.dir/ODsay.o: header/rapidjson/allocators.h
src/TOMSA.dir/ODsay.o: header/rapidjson/document.h
src/TOMSA.dir/ODsay.o: header/rapidjson/encodedstream.h
src/TOMSA.dir/ODsay.o: header/rapidjson/encodings.h
src/TOMSA.dir/ODsay.o: header/rapidjson/error/error.h
src/TOMSA.dir/ODsay.o: header/rapidjson/internal/biginteger.h
src/TOMSA.dir/ODsay.o: header/rapidjson/internal/diyfp.h
src/TOMSA.dir/ODsay.o: header/rapidjson/internal/ieee754.h
src/TOMSA.dir/ODsay.o: header/rapidjson/internal/meta.h
src/TOMSA.dir/ODsay.o: header/rapidjson/internal/pow10.h
src/TOMSA.dir/ODsay.o: header/rapidjson/internal/stack.h
src/TOMSA.dir/ODsay.o: header/rapidjson/internal/strfunc.h
src/TOMSA.dir/ODsay.o: header/rapidjson/internal/strtod.h
src/TOMSA.dir/ODsay.o: header/rapidjson/internal/swap.h
src/TOMSA.dir/ODsay.o: header/rapidjson/memorystream.h
src/TOMSA.dir/ODsay.o: header/rapidjson/msinttypes/inttypes.h
src/TOMSA.dir/ODsay.o: header/rapidjson/msinttypes/stdint.h
src/TOMSA.dir/ODsay.o: header/rapidjson/rapidjson.h
src/TOMSA.dir/ODsay.o: header/rapidjson/reader.h
src/TOMSA.dir/ODsay.o: header/rapidjson/stream.h

src/TOMSA.dir/PointInPolygonAlgorithm.o: src/PointInPolygonAlgorithm.cpp
src/TOMSA.dir/PointInPolygonAlgorithm.o: header/Line.h
src/TOMSA.dir/PointInPolygonAlgorithm.o: header/PointInPolygonAlgorithm.h
src/TOMSA.dir/PointInPolygonAlgorithm.o: header/Position.h

src/TOMSA.dir/Position.o: src/Position.cpp
src/TOMSA.dir/Position.o: header/Position.h

src/TOMSA.dir/TimeOptimizationAlgorithm.o: src/TimeOptimizationAlgorithm.cpp
src/TOMSA.dir/TimeOptimizationAlgorithm.o: header/Line.h
src/TOMSA.dir/TimeOptimizationAlgorithm.o: header/PointInPolygonAlgorithm.h
src/TOMSA.dir/TimeOptimizationAlgorithm.o: header/Position.h
src/TOMSA.dir/TimeOptimizationAlgorithm.o: header/TimeOptimizationAlgorithm.h

src/TOMSA.dir/main.o: src/main.cpp
src/TOMSA.dir/main.o: header/ConcavetToConvex.h
src/TOMSA.dir/main.o: header/Line.h
src/TOMSA.dir/main.o: header/ODsay.h
src/TOMSA.dir/main.o: header/PointInPolygonAlgorithm.h
src/TOMSA.dir/main.o: header/Position.h
src/TOMSA.dir/main.o: header/TimeOptimizationAlgorithm.h
src/TOMSA.dir/main.o: header/rapidjson/allocators.h
src/TOMSA.dir/main.o: header/rapidjson/document.h
src/TOMSA.dir/main.o: header/rapidjson/encodedstream.h
src/TOMSA.dir/main.o: header/rapidjson/encodings.h
src/TOMSA.dir/main.o: header/rapidjson/error/error.h
src/TOMSA.dir/main.o: header/rapidjson/internal/biginteger.h
src/TOMSA.dir/main.o: header/rapidjson/internal/diyfp.h
src/TOMSA.dir/main.o: header/rapidjson/internal/ieee754.h
src/TOMSA.dir/main.o: header/rapidjson/internal/meta.h
src/TOMSA.dir/main.o: header/rapidjson/internal/pow10.h
src/TOMSA.dir/main.o: header/rapidjson/internal/stack.h
src/TOMSA.dir/main.o: header/rapidjson/internal/strfunc.h
src/TOMSA.dir/main.o: header/rapidjson/internal/strtod.h
src/TOMSA.dir/main.o: header/rapidjson/internal/swap.h
src/TOMSA.dir/main.o: header/rapidjson/memorystream.h
src/TOMSA.dir/main.o: header/rapidjson/msinttypes/inttypes.h
src/TOMSA.dir/main.o: header/rapidjson/msinttypes/stdint.h
src/TOMSA.dir/main.o: header/rapidjson/rapidjson.h
src/TOMSA.dir/main.o: header/rapidjson/reader.h
src/TOMSA.dir/main.o: header/rapidjson/stream.h

