# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# compile CXX with /usr/bin/c++
CXX_FLAGS =   -std=c++11

CXX_DEFINES = 

CXX_INCLUDES = -I/header -I/home/kuril/workspace/DamoyeoServer/header 

